### PR TITLE
Update the target 'clean' rule

### PR DESCRIPTION
**Pull request by EvilGodEX**
I updated the rule of clean so that DTC binary and DTC intermediate files at compile time can be cleaned together when 'make clean'

### CODE REVIEW

**Comment by gesangtome** [comment]
Can one of the admins verify this patch?

**Comment by EvilGodEX** [comment]
> Can one of the admins verify this patch?

run tests

**Comment by gesangtome** [comment]
> Can one of the admins verify this patch?

run tests

**Comment by gesangtome** [comment]
@EvilGodEX  Good idea. Good job

**Pull request merged**
